on:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Check Shapefile exists
        run: |
          ls -l viz/data/
          file viz/data/2024-12-02_delim-parcellaire-aoc-shp.shp  
      
      - name: Set CRAN mirror for renv
        run: echo "RENV_CONFIG_REPOS_OVERRIDE=https://cran.r-project.org" >> ~/.Renviron
      
      - name: Set up system dependencies 
        run: | 
          sudo apt-get update 
          sudo apt-get install -y libproj-dev gdal-bin libudunits2-dev libgdal-dev libharfbuzz-dev libfribidi-dev

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
      
      - name: Disable renv sandbox
        run: echo "RENV_CONFIG_SANDBOX_ENABLED=false" >> ~/.Renviron

      - name: Fix renv.lock file
        run: |
          sed -i 's|http://pbil.univ-lyon1.fr/CRAN|https://cran.r-project.org|g' renv.lock
      
      - name: Restore dependencies with fixed CRAN mirror
        run: Rscript -e 'options(repos = c(CRAN = "https://cran.r-project.org")); renv::restore()'

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
